### ISSUE TITLE
Minimal internal image conversion inside cmdthumbgen?

### ISSUE THREAD

**Issue by tumagonx** [kenjiuno/ThumbGensPack#4]
There is lot of unix-like origin image converter that doesn't support bmp format output, mostly default to png. Is there a plan to have internal conversion for non-24bit bmp image such png, say, using gdi+?

I know I could use pipe with png2bmp but it would be more convenient to do it internally. thanks.

**Comment by tumagonx** [comment]
example of really good and fast (probably fastest) thumbnailer: vipsthumbnails (of Libvips)
www.vips.ecs.soton.ac.uk/index.php?title=Libvips
https://www.peterbe.com/plog/vipsthumbnail

thanks.

**Comment by kenjiuno** [comment]
[They](http://stackoverflow.com/a/4568205) say that [Windows Imaging Component](https://msdn.microsoft.com/en-us/library/ee719902(v=VS.85).aspx) can read png.

I have written WIC support code today. https://github.com/kenjiuno/ThumbGensPack/commit/227366dd9c2543f361d64c27d6ff0d43fd5fbb8f
I'll test whether it can handle .png and .jpg files, or not.

**Comment by kenjiuno** [comment]
1.2.14 is released for testing. https://github.com/kenjiuno/ThumbGensPack/releases
`Suffix` is supported. doc updated: https://github.com/kenjiuno/ThumbGensPack/blob/master/README.md

**Comment by tumagonx** [comment]
Works great on XP32 or XP64  as long as WIC installed
